rule all:
    input:
        "analysis_figures/nationality_proportions_by_museum.png",
        "analysis_figures/birth_year_trends_met.png",
        "analysis_figures/birth_year_trends_moma.png"

rule download_moma:
    output:
        artists="data/moma_artists.csv",
        artworks="data/moma_artworks.csv"
    script:
        "scripts/download_moma.py"


rule download_met:
    output:
        "data/met_objects.csv"
    script:
        "scripts/download_met.py"

rule clean_moma:
    input:
        artists="data/moma_artists.csv",
        artworks="data/moma_artworks.csv"
    output:
        "results/moma_snakefile_cleaned.csv"
    script:
        "scripts/clean_moma.py"

rule clean_met:
    input:
        "data/met_objects.csv"
    output:
        "results/met_snakefile_cleaned.csv"
    script:
        "scripts/clean_met.py"

rule openrefine_moma:
    input:
        data="results/moma_snakefile_cleaned.csv",
        operations="apply_openrefine_to_moma.json"
    output:
        "results/final_moma.csv"
    script:
        "scripts/apply_openrefine.py"

rule openrefine_met:
    input:
        data="results/met_snakefile_cleaned.csv",
        operations="apply_openrefine_to_met.json"
    output:
        "results/final_met.csv"
    script:
        "scripts/apply_openrefine.py"

rule combine:
    input:
        moma="results/final_moma.csv",
        met="results/final_met.csv"
    output:
        "results/combined_moma_met.csv"
    script:
        "scripts/combine.py"

rule analysis:
    input:
        "results/combined_moma_met.csv"
    output:
        "analysis_figures/nationality_proportions_by_museum.png",
        "analysis_figures/birth_year_trends_met.png",
        "analysis_figures/birth_year_trends_moma.png"
    script:
        "scripts/analysis.py"
